services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "8080:8080"
    volumes:
      - ./mlflow_data:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 8080
      --backend-store-uri sqlite:///mlflow_data/mlflow.db